#lang scheme
(provide f)
(require "../examples/square")
(define (sum-of-squares a b c)
  (+ (square a) (square b) (square c)))
(define (f a b c)
  (- (sum-of-squares a b c)
     (cond ((and (< a b) (< a c)) a)
           ((and (< b a) (< b c)) b)
           ((and (< c a) (< c b)) c))))
