#lang scheme
(provide simpson)
(require "../examples/sum")
(define (simpson f a b n)
  (define h (/ (- b a) n))
  (define (term k)
    (* (q k) (y k)))
  (define (q k)
    (cond ((or (= k 0) (= k n)) 1)
          ((= (remainder k 2) 0) 2)
          (else 4)))
  (define (y k)
    (f (+ a (* k h))))
  (define (inc k) (+ k 1))
  (* (/ h 3.0) (sum term 0 inc n)))
