#lang scheme
(provide exp-e)
(require "ex137")
(define (exp-e k)
  (cont-frac (lambda (i) 1.0)
             (lambda (i)
               (if (= (remainder (+ i 1) 3) 0)
                   (* 2 (/ (+ i 1) 3))
                   1))
             k))
