#lang scheme
(require "../examples/prime")
(define (runtime) (current-milliseconds))
(define (range-prime-test a b)
  (if (even? a) (range-prime-test (+ a 1) b)
      (cond ((> a b) (newline) (display "Done"))
            (else (timed-prime-test a)
                  (range-prime-test (+ a 2) b)))))
(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime)))
(define (start-prime-test n start-time)
  (when (prime? n)
      (report-prime (- (runtime) start-time))))
(define (report-prime elapsed-time)
  (display " *** ")
  (display elapsed-time))
(range-prime-test 1000 1050)
(range-prime-test 10000 10050)
(range-prime-test 100000 100050)
(range-prime-test 1000000 1000050)
(newline)
