#lang scheme
(require "../examples/expmod")
(define (full-fermat-test n)
  (test-range 1 n))
(define (test-range m n)
  (define (try-it a)
    (= (expmod a n n) a))
  (cond ((= m n) true)
        ((try-it m) (test-range (+ m 1) n))
        (else false)))
(full-fermat-test 561)
(full-fermat-test 1105)
(full-fermat-test 1729)
(full-fermat-test 2465)
(full-fermat-test 2821)
(full-fermat-test 6601)
