#lang scheme
(define (square x) (* x x))
(define (prime? n)
  (= n (smallest-divisor n)))
(define (smallest-divisor n) (find-divisor n 2))
(define (find-divisor n test-divisor)
  (cond ((> (square test-divisor) n) n)
        ((divides? test-divisor n) test-divisor)
        (else (find-divisor n (next test-divisor)))))
(define (divides? a b) (= (remainder b a) 0))
(define (next n) (if (= n 2) 3 (+ n 2)))
(define (runtime) (current-milliseconds))
(define (range-prime-test a b)
  (if (even? a) (range-prime-test (+ a 1) b)
      (cond ((> a b) (newline) (display "Done"))
            (else (timed-prime-test a)
                  (range-prime-test (+ a 2) b)))))
(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime)))
(define (start-prime-test n start-time)
  (when (prime? n)
      (report-prime (- (runtime) start-time))))
(define (report-prime elapsed-time)
  (display " *** ")
  (display elapsed-time))
(range-prime-test 1000 1050)
(range-prime-test 10000 10050)
(range-prime-test 100000 100050)
(range-prime-test 1000000 1000050)
(newline)
